version: 2

sources:
  - name: mysql_rds_sakila
    database: sakila_raw
    tables:
      - name: actor
      - name: address
      - name: category
      - name: store
      - name: staff
      - name: customer
      - name: country
      - name: city
      - name: rental
      - name: film
      - name: film_category
      - name: language
      - name: payment
      - name: inventory
  
  - name: dbt_achakravorty
    database: sakila_dw
    tables:
      - name: dim_date
      - name: dim_timeofday